baseUrl = "https://pyonk.github.io/blog/"
theme = "pyonk"
defaultContentLanguage = "ja"
enableEmoji = true

[taxonomies]
  tag = "tags"
  category = "categories"

[main]
  content = "./content/"

[services]
  [services.googleAnalytics]
    ID = "G-51GX3P4YPL"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 0
  showReadingTime = true

  # Social links
  github = "https://github.com/pyonk"
  linkedin = "https://www.linkedin.com/in/pyonk"


[markup]
  [markup.blackFriday]
    hrefTargetBlank = true

[pagination]
    pagerSize = 5

[languages]
  [languages.ja]
    title = "ã‚ã„ãŒã‹ã„ãŸ"

    [languages.ja.params]
      keywords = "ã‚ã„ãŒã‹ã„ãŸ"
      [languages.ja.params.logo]
        logoText = "ã‚ã„ãŒã‹ã„ãŸ"
        logoHomeLink = "/blog/"

    [[languages.ja.menu.main]]
      name = "ğŸ“·"
      url = "/gallery/"
      weight = 10

  [languages.en]
    title = "waigakaita"

    [languages.en.params]
      keywords = "waigakaita"
      [languages.en.params.logo]
        logoText = "waigakaita"
        logoHomeLink = "/blog/"

    [[languages.en.menu.main]]
      name = "ğŸ“·"
      url = "/gallery/"
      weight = 10

